name: "Change Request"
description: File a Change Request for API Economy Products report
title: "[Change Request]:"
labels: feature
assignees:
  - Vaidyeshwaran-S
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this Change Request report!
  - type: input
    id: contact
    attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
    validations:
    required:false
  - type: textarea
    id: what-feature
    attributes:
      label: Request Info?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Brief Changes"
    validations:
      required:true
  - type: dropdown
    id: test
    attributes:
      label: Version
      description:brief
      options:
        - APIc (Default)
        - BlueAPI 
        - APIHub
  - type: textarea
    id: Description
    attributes:
      label: Relevant Change Request Description
      description: Please copy and paste any relevant detail description
      render: shell
 
