name: "Feature Form"
description: "Use this form for creating new features."
title: "Feature Request"
labels: ["feature"]
assignees:
  - Vaidyeshwaran-S
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this Change Request report!
  - type:input
    id:contact
    attributes:
    label: Contact
        description: How can we get in touch with you if we need more info?
        placeholder: ex. email@example.com
    validations:
    required: false
  - type: dropdown
    id: test
    attributes:
      label: API Components
      description: brief
      options:
        - APIc (Default)
        - BlueAPI 
        - APIHub
  - type: textarea
    attributes:
      label: "Overview"
      description: "Provide an overview of the feature request."
      placeholder: "Provide information here."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Requirements"
      description: "List all requirements for ticket completion."
      placeholder: "- [ ] List Requirements Here"
      value: "- [ ] Requirement 1"
  - type: textarea
    attributes:
      label: "Related Tickets"
      description: "Link to any related or prior tickets."
      placeholder: "List related tickets here if available."
      value: "- #"
  - type: textarea
    attributes:
      label: "Screenshots (if applicable)"
      description: "Provide any relevant screenshots."
      placeholder: "Add relevant screenshots here."
