name: "Feature Form1"
description: "Use this form for creating new features."
title: "Feature1 Request1"
labels: ["feature"]
assignees:
  - Vaidyeshwaran-S
body:
  - type: textarea
    attributes:
      label: "Overview"
      description: "Provide an overview of the feature request."
      placeholder: "Provide information here."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Requirements"
      description: "List all requirements for ticket completion."
      placeholder: "- [ ] List Requirements Here"
      value: "- [ ] Requirement 1"
  - type: textarea
    attributes:
      label: "Related Tickets"
      description: "Link to any related or prior tickets."
      placeholder: "List related tickets here if available."
      value: "- #"
  - type: textarea
    attributes:
      label: "Screenshots (if applicable)"
      description: "Provide any relevant screenshots."
      placeholder: "Add relevant screenshots here."
